export type FileTypeGroup =
  'archive' | 'code' | 'document' | 'image' | 'media' | 'other' | 'text'

import type { PreviewKind } from '../preview/index.ts'

export type FileTypeAdapterId = 'json' | 'svg' | 'xml'

export interface FileTypeConversionConfig {
  allowUtf8Source: boolean
  allowDecodedBytes: boolean
}

export interface FileTypeConfig {
  id: string
  label: string
  group: FileTypeGroup
  extensions: readonly string[]
  mimeTypes: readonly string[]
  previewKind: PreviewKind
  conversion: FileTypeConversionConfig
  adapter?: FileTypeAdapterId
  autoRecommend?: boolean
  autoRecommendPriority?: number
}

export const utf8Conversion = {
  allowUtf8Source: true,
  allowDecodedBytes: true,
} as const satisfies FileTypeConversionConfig

export const decodedConversion = {
  allowUtf8Source: false,
  allowDecodedBytes: true,
} as const satisfies FileTypeConversionConfig

export const FILE_TYPE_CONFIG = [
  {
    id: 'txt',
    label: 'TXT',
    group: 'text',
    extensions: ['txt'],
    mimeTypes: ['text/plain'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'markdown',
    label: 'MD',
    group: 'document',
    extensions: ['md', 'markdown'],
    mimeTypes: ['text/markdown'],
    previewKind: 'markdown',
    conversion: utf8Conversion,
  },
  {
    id: 'csv',
    label: 'CSV',
    group: 'text',
    extensions: ['csv'],
    mimeTypes: ['text/csv'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'tsv',
    label: 'TSV',
    group: 'text',
    extensions: ['tsv'],
    mimeTypes: ['text/tab-separated-values'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'xml',
    label: 'XML',
    group: 'code',
    extensions: ['xml'],
    mimeTypes: ['application/xml', 'text/xml'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
    adapter: 'xml',
    autoRecommend: true,
    autoRecommendPriority: 30,
  },
  {
    id: 'yaml',
    label: 'YAML',
    group: 'code',
    extensions: ['yaml', 'yml'],
    mimeTypes: ['application/yaml', 'text/yaml'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'json',
    label: 'JSON',
    group: 'code',
    extensions: ['json'],
    mimeTypes: ['application/json', 'text/json'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
    adapter: 'json',
    autoRecommend: true,
    autoRecommendPriority: 10,
  },
  {
    id: 'html',
    label: 'HTML',
    group: 'code',
    extensions: ['html', 'htm'],
    mimeTypes: ['text/html'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'css',
    label: 'CSS',
    group: 'code',
    extensions: ['css'],
    mimeTypes: ['text/css'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'javascript',
    label: 'JS',
    group: 'code',
    extensions: ['js', 'mjs', 'cjs', 'jsx'],
    mimeTypes: ['application/javascript', 'text/javascript'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'typescript',
    label: 'TS',
    group: 'code',
    extensions: ['ts', 'tsx', 'mts', 'cts'],
    mimeTypes: ['application/typescript', 'text/typescript'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'python',
    label: 'Python',
    group: 'code',
    extensions: ['py', 'pyw', 'pyi'],
    mimeTypes: ['text/x-python', 'application/x-python-code'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'go',
    label: 'Go',
    group: 'code',
    extensions: ['go'],
    mimeTypes: ['text/x-go'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'rust',
    label: 'Rust',
    group: 'code',
    extensions: ['rs'],
    mimeTypes: ['text/x-rust'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'java',
    label: 'Java',
    group: 'code',
    extensions: ['java'],
    mimeTypes: ['text/x-java-source', 'text/x-java'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'c',
    label: 'C',
    group: 'code',
    extensions: ['c', 'h'],
    mimeTypes: ['text/x-c', 'text/x-csrc', 'text/x-chdr'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'cpp',
    label: 'C++',
    group: 'code',
    extensions: ['cpp', 'cc', 'cxx', 'hpp', 'hh', 'hxx'],
    mimeTypes: ['text/x-c++src', 'text/x-c++hdr'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'csharp',
    label: 'C#',
    group: 'code',
    extensions: ['cs'],
    mimeTypes: ['text/x-csharp'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'php',
    label: 'PHP',
    group: 'code',
    extensions: ['php', 'phtml'],
    mimeTypes: ['application/x-httpd-php', 'text/x-php'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'ruby',
    label: 'Ruby',
    group: 'code',
    extensions: ['rb', 'rake', 'gemspec'],
    mimeTypes: ['application/x-ruby', 'text/x-ruby'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'swift',
    label: 'Swift',
    group: 'code',
    extensions: ['swift'],
    mimeTypes: ['text/x-swift'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'kotlin',
    label: 'Kotlin',
    group: 'code',
    extensions: ['kt', 'kts'],
    mimeTypes: ['text/x-kotlin'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'scala',
    label: 'Scala',
    group: 'code',
    extensions: ['scala', 'sc'],
    mimeTypes: ['text/x-scala'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'dart',
    label: 'Dart',
    group: 'code',
    extensions: ['dart'],
    mimeTypes: ['application/vnd.dart', 'text/x-dart'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'shell',
    label: 'Shell',
    group: 'code',
    extensions: ['sh', 'bash', 'zsh', 'fish'],
    mimeTypes: [
      'application/x-sh',
      'application/x-shellscript',
      'text/x-shellscript',
    ],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'powershell',
    label: 'PowerShell',
    group: 'code',
    extensions: ['ps1', 'psm1', 'psd1'],
    mimeTypes: ['text/x-powershell'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'batch',
    label: 'BAT',
    group: 'code',
    extensions: ['bat', 'cmd'],
    mimeTypes: ['application/x-bat'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'sql',
    label: 'SQL',
    group: 'code',
    extensions: ['sql'],
    mimeTypes: ['application/sql', 'text/x-sql'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'lua',
    label: 'Lua',
    group: 'code',
    extensions: ['lua'],
    mimeTypes: ['text/x-lua'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'r',
    label: 'R',
    group: 'code',
    extensions: ['r', 'rmd'],
    mimeTypes: ['text/x-r-source'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'vue',
    label: 'Vue',
    group: 'code',
    extensions: ['vue'],
    mimeTypes: ['text/x-vue'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'svelte',
    label: 'Svelte',
    group: 'code',
    extensions: ['svelte'],
    mimeTypes: ['text/x-svelte'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'scss',
    label: 'SCSS',
    group: 'code',
    extensions: ['scss'],
    mimeTypes: ['text/x-scss'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'sass',
    label: 'Sass',
    group: 'code',
    extensions: ['sass'],
    mimeTypes: ['text/x-sass'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'less',
    label: 'Less',
    group: 'code',
    extensions: ['less'],
    mimeTypes: ['text/x-less'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'toml',
    label: 'TOML',
    group: 'code',
    extensions: ['toml'],
    mimeTypes: ['application/toml'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'ini',
    label: 'INI',
    group: 'code',
    extensions: ['ini', 'cfg', 'conf'],
    mimeTypes: ['text/x-ini'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'graphql',
    label: 'GraphQL',
    group: 'code',
    extensions: ['graphql', 'gql'],
    mimeTypes: ['application/graphql'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'protobuf',
    label: 'Protobuf',
    group: 'code',
    extensions: ['proto'],
    mimeTypes: ['text/x-protobuf'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
  },
  {
    id: 'patch',
    label: 'PATCH',
    group: 'code',
    extensions: ['patch', 'diff'],
    mimeTypes: ['text/x-patch', 'text/x-diff'],
    previewKind: 'diff',
    conversion: utf8Conversion,
  },
  {
    id: 'svg',
    label: 'SVG',
    group: 'code',
    extensions: ['svg'],
    mimeTypes: ['image/svg+xml'],
    previewKind: 'plain-text',
    conversion: utf8Conversion,
    adapter: 'svg',
    autoRecommend: true,
    autoRecommendPriority: 20,
  },
  {
    id: 'png',
    label: 'PNG',
    group: 'image',
    extensions: ['png'],
    mimeTypes: ['image/png'],
    previewKind: 'raster-image',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'jpeg',
    label: 'JPG',
    group: 'image',
    extensions: ['jpg', 'jpeg'],
    mimeTypes: ['image/jpeg'],
    previewKind: 'raster-image',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'webp',
    label: 'WebP',
    group: 'image',
    extensions: ['webp'],
    mimeTypes: ['image/webp'],
    previewKind: 'raster-image',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'gif',
    label: 'GIF',
    group: 'image',
    extensions: ['gif'],
    mimeTypes: ['image/gif'],
    previewKind: 'raster-image',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'mp3',
    label: 'MP3',
    group: 'media',
    extensions: ['mp3'],
    mimeTypes: ['audio/mpeg', 'audio/mp3'],
    previewKind: 'audio',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'wav',
    label: 'WAV',
    group: 'media',
    extensions: ['wav'],
    mimeTypes: ['audio/wav', 'audio/x-wav'],
    previewKind: 'audio',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'ogg',
    label: 'OGG',
    group: 'media',
    extensions: ['ogg', 'oga'],
    mimeTypes: ['audio/ogg'],
    previewKind: 'audio',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'opus',
    label: 'Opus',
    group: 'media',
    extensions: ['opus'],
    mimeTypes: ['audio/opus'],
    previewKind: 'audio',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'flac',
    label: 'FLAC',
    group: 'media',
    extensions: ['flac'],
    mimeTypes: ['audio/flac', 'audio/x-flac'],
    previewKind: 'audio',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'aac',
    label: 'AAC',
    group: 'media',
    extensions: ['aac'],
    mimeTypes: ['audio/aac'],
    previewKind: 'audio',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'm4a',
    label: 'M4A',
    group: 'media',
    extensions: ['m4a'],
    mimeTypes: ['audio/mp4', 'audio/x-m4a'],
    previewKind: 'audio',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'mp4',
    label: 'MP4',
    group: 'media',
    extensions: ['mp4'],
    mimeTypes: ['video/mp4'],
    previewKind: 'video',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'webm',
    label: 'WebM',
    group: 'media',
    extensions: ['webm'],
    mimeTypes: ['video/webm'],
    previewKind: 'video',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'mov',
    label: 'MOV',
    group: 'media',
    extensions: ['mov'],
    mimeTypes: ['video/quicktime'],
    previewKind: 'video',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'm4v',
    label: 'M4V',
    group: 'media',
    extensions: ['m4v'],
    mimeTypes: ['video/x-m4v'],
    previewKind: 'video',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'ogv',
    label: 'OGV',
    group: 'media',
    extensions: ['ogv'],
    mimeTypes: ['video/ogg'],
    previewKind: 'video',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'avi',
    label: 'AVI',
    group: 'media',
    extensions: ['avi'],
    mimeTypes: ['video/x-msvideo', 'video/vnd.avi'],
    previewKind: 'video',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'mkv',
    label: 'MKV',
    group: 'media',
    extensions: ['mkv'],
    mimeTypes: ['video/x-matroska'],
    previewKind: 'video',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'pdf',
    label: 'PDF',
    group: 'document',
    extensions: ['pdf'],
    mimeTypes: ['application/pdf'],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'docx',
    label: 'DOCX',
    group: 'document',
    extensions: ['docx'],
    mimeTypes: [
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
  },
  {
    id: 'xlsx',
    label: 'XLSX',
    group: 'document',
    extensions: ['xlsx'],
    mimeTypes: [
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    ],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
  },
  {
    id: 'pptx',
    label: 'PPTX',
    group: 'document',
    extensions: ['pptx'],
    mimeTypes: [
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    ],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
  },
  {
    id: 'zip',
    label: 'ZIP',
    group: 'archive',
    extensions: ['zip'],
    mimeTypes: ['application/zip', 'application/x-zip-compressed'],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'gzip',
    label: 'GZIP',
    group: 'archive',
    extensions: ['gz', 'gzip'],
    mimeTypes: ['application/gzip'],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'seven-zip',
    label: '7Z',
    group: 'archive',
    extensions: ['7z'],
    mimeTypes: ['application/x-7z-compressed'],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'rar',
    label: 'RAR',
    group: 'archive',
    extensions: ['rar'],
    mimeTypes: ['application/vnd.rar', 'application/x-rar-compressed'],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
    autoRecommend: true,
  },
  {
    id: 'custom',
    label: 'FILE',
    group: 'other',
    extensions: [],
    mimeTypes: [],
    previewKind: 'metadata-only',
    conversion: utf8Conversion,
  },
  {
    id: 'unknown',
    label: 'UNKNOWN',
    group: 'other',
    extensions: [],
    mimeTypes: [],
    previewKind: 'metadata-only',
    conversion: decodedConversion,
  },
] as const satisfies readonly FileTypeConfig[]

export type ConfiguredFileTypeId = (typeof FILE_TYPE_CONFIG)[number]['id']
